name = "rpg-nuxt-app"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2024-05-01"

[placement]
mode = "smart"

[limits]
cpu_ms = 10000

[site]
bucket = "./.output/public"
